# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Beatiful Tragedy
email: amanda.iaria@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 The Portfolio of Amanda Iaria. Full Stack Web Developer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://beautiful-tragedy.com" # the base hostname & protocol for your site
twitter_username: tragiclyhipster
github_username:  amanda.iaria
codepen_username: amanda.iaria
linkedin_username: amanda.iaria
instagram_username: tragicallyh1pster

# Build settings
markdown: kramdown

#exclude files
exclude: [ node_modules, Gruntfile.js, package.json, .bowerrc, .gitignore ]